version: '3.9'

services:
  app:
    image: node:18.12.1
    volumes:
    - .:/ws
    working_dir: /ws/app
    restart: always
    ports:
    - 14000:14000
    entrypoint: bash -c "npm install && npm start"
    environment:
      PORT: 14000
      HOST: 0.0.0.0

  api:
    image: node:18.12.1
    volumes:
    - .:/ws
    - ./api/.env:/opt/projects/movie/api/.env
    working_dir: /ws/api
    entrypoint: bash -c "npm install && npm start"
    ports:
    - 15000:3000
    restart: always

  db:
    image: postgres:15.1-alpine3.16
    restart: always
    volumes:
    - .:/ws
    ports:
    - 5432
    environment:
      POSTGRES_PASSWORD: postgres12345678

  adminer:
    image: adminer
    restart: always
    ports:
    - 15432:8080

  e2e:
    image: cypress/included:11.2.0
    volumes:
    - .:/ws
    working_dir: /ws/e2e
    entrypoint: bash -c "export \$(cat .env | xargs) && yarn test \$(cat .specs)"
    env_file:
    - e2e/.env
