version: '3.9'

services:
  app:
    image: node:18.12.1
    volumes:
    - .:/ws
    working_dir: /ws/app
    restart: always
    ports:
    - 14000:3000
    image: node:18.12.1
    volumes:
    - .:/ws
    working_dir: /ws
    entrypoint: bash -c "tail -f"
