version: '3.9'

services:
  app:
    image: node:18.12.1
    volumes:
    - .:/ws
    working_dir: /ws/app
    restart: always
    ports:
    - 14000:3000
    entrypoint: bash -c "npm start"
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    image: node:18.12.1
    volumes:
    - .:/ws
    working_dir: /ws
    entrypoint: bash -c "tail -f"
